name: App Staging

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "LICENSE"
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    name: Builds Docker Image for beta release
    runs-on: ubuntu-20.04
    strategy:
          matrix:
            python-version: [ '3.8', '3.9', '3.10' ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get version number 
        id: version_number
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './portainer_deployer/ver.json'
          prop_path: 'version'
      
      - name: Get phase 
        id: version_phase
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './portainer_deployer/ver.json'
          prop_path: 'phase'

      - run: |
          echo ${{steps.version_number.outputs.prop}} 
          echo ${{steps.version_phase.outputs.prop}} 

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:
    