name: App Staging

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "LICENSE"
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.event.repository.name }}
  # Recommended python version for the project
  STABLE_PYTHON_VER: 3.8

jobs:
  # Create a job for getting tags and lowercase version info
  versioning:
    name: Get versioning info to export
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.version_number.outputs.prop }} 
      phase: ${{ steps.version_phase_lower.outputs.lowercase }} 

    steps:
      - name: Download source code
        uses: actions/checkout@v3
    
      - name: Get version number 
        id: version_number
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './portainer_deployer/info.json'
          prop_path: 'version'
      
      - name: Get version phase (Capitalized)
        id: version_phase_cap
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './portainer_deployer/info.json'
          prop_path: 'phase'

      - name: Get version phase (Lowercase)
        id: version_phase_lower
        uses: ASzc/change-string-case-action@v2
        with: 
          string: ${{steps.version_phase_cap.outputs.prop}}


  build-docker:
    name: Builds Docker Image for beta release
    runs-on: ubuntu-20.04
    strategy:
          matrix:
            python-version: [ '3.8', '3.9', '3.10' ]
    needs: [ versioning ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ matrix.python-version }} == ${{ env.STABLE_PYTHON_VER }}
        with:
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:dev         
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{needs.versioning.outputs.version}}-${{needs.versioning.outputs.phase}}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.pull_request.head.sha }}
            
      - name: Build and push with matrix
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:dev-python${{ matrix.python-version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{needs.versioning.outputs.version}}-${{needs.versioning.outputs.phase}}-python${{ matrix.python-version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-python${{ matrix.python-version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.pull_request.head.sha }}-python${{ matrix.python-version }}
    